ARG GO_VERSION=1.23.5
FROM golang:${GO_VERSION}-alpine


WORKDIR /src

COPY go.mod go.sum ./
RUN go mod download


COPY . .

# Build the Go app
ARG TARGETARCH
RUN CGO_ENABLED=0 GOARCH=${TARGETARCH} go build -o /bin/server .

# # Giving permission to the binary
# RUN chmod +x /bin/server

# Expose port 8080 to the outside world
EXPOSE 8080

# Command to run the executable
CMD ["/bin/server"]
